batch_size: [128] 
dataset: ["ogbg-molhiv"]
drop_out: [0.5] 
emb_dim: [64] 
epochs: [100] 
lr: [0.001] 
lr_scheduler: ["None"] 
lstm_depth: [2] 
model: ["pathGNN"] 
num_layer: [1] 
num_mlp_layers: [1] 
path_length: [4] 
pooling: ["mean"]
reverse: [1] 
share_lstm: [1]
mark_neighbors: [1]
path_pooling: ["sum"]
JK: ["mean"]