batch_size: [32] 
dataset: ["ogbg-moltox21"]
drop_out: [0.5] 
emb_dim: [256] 
epochs: [200] 
lr: [0.0001] 
lr_scheduler: ["None"] 
lstm_depth: [2] 
model: ["pathGNN"] 
num_layer: [5] 
num_mlp_layers: [2] 
path_length: [3] 
pooling: ["mean"]
reverse: [1] 
share_lstm: [1]
mark_neighbors: [1]
path_pooling: ["sum"]