batch_size: [128] 
dataset: ["ZINC"]
drop_out: [0] 
emb_dim: [128] 
epochs: [1000] 
lr: [0.001] 
lr_schedule_patience: [20] 
lr_scheduler_decay_rate: [0.5] 
lstm_depth: [2] 
min_lr: [1e-05] 
model: ["pathGNN"] 
num_layer: [5] 
num_mlp_layers: [2] 
path_length: [3] 
pooling: ["sum"]
reverse: [1] 
share_lstm: [1]
mark_neighbors: [1]
path_pooling: ["sum"]