
epochs: [500]
model: ["pathGNN-S"]
batch_size: [8]
emb_dim: [16]
drop_out: [0.0]
lr:  [5e-4]
lr_schedule_patience: [20]
tracking: [1]
min_lr: [1e-6]
lr_scheduler: ["None"]
lstm_depth: [1]
share_lstm: [0]
num_mlp_layers: [2]
pooling: ["sum"]
path_pooling: ["mean"]
num_layers: [3]
path_length: [2]
mark_neighbors: [0]
