
epochs: [500]
model: ["pathGNN-S"]
batch_size: [8]
emb_dim: [16]
drop_out: [0.0]
lr:  [1e-4]
tracking: [1]
lr_scheduler: ["None"]
lstm_depth: [1]
share_lstm: [0]
pooling: ["mean"]
num_layers: [2]
path_length: [2]
mark_neighbors: [0]
